In [1]:
import gmaps
import numpy as np
import pandas as pd

In [2]:
gkey = "AIzaSyDkwm-MsLDHq79iRGf9BX5mXQ7xKOHNY6s"

In [3]:
df = pd.read_csv("GameResultsLatsLongs.csv")
df.head()

,Game ID,Week,Date,Time (EST),Location,Home Team,Away Team,Home Score,Away Score,Total Points,...,Away QB Rating,Away Passing TDs,Away Interceptions,Away First Downs,Away FG Attempts,Away FG Made,Away Punts,Indoor,Lat,Lng
0,45944,1,2018-09-06,8:20PM,Lincoln Financial Field,PHI,ATL,18,12,30,...,57.4,0,1,16,2,2,6,False,39.900833,-75.167500
1,45945,1,2018-09-09,1:00PM,M&T Bank Stadium,BAL,BUF,47,3,50,...,17.1,0,2,10,2,1,8,False,39.278056,-76.622778
2,45946,1,2018-09-09,1:00PM,Lucas Oil Stadium,IND,CIN,23,34,57,...,109.7,2,1,19,2,2,2,True,39.760056,-86.163806
3,45947,1,2018-09-09,1:00PM,Gillette Stadium,NE,HOU,27,20,47,...,62.9,1,1,21,2,2,6,False,42.090944,-71.264344
4,45948,1,2018-09-09,1:00PM,MetLife Stadium,NYG,JAX,15,20,35,...,67.2,1,1,17,2,2,7,False,40.813528,-74.074361

In [4]:
locations = df[["Lat", "Lng"]].astype(float)

In [5]:
scoring = df["Total Points"].astype(float)

In [7]:
gmaps.configure(api_key=gkey)

In [16]:
fig = gmaps.figure()
heat_layer = gmaps.heatmap_layer(locations, weights=scoring*.3, 
                                 dissipating=False, max_intensity=100,
                                 point_radius = 100)
heat_layer.dissipating = False
heat_layer.max_intensity = 100
heat_layer.point_radius = .5

Figure(layout=FigureLayout(height='420px'))